development:
  adapter: postgresql
  encoding: unicode
  database: url-shortener_development
  pool: 5
  username: postgres
  password:
  host: localhost
  encoding: utf8
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: url-shortener_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8
  template: template0